### ISSUE TITLE
Question: Are the images meant to be readable to human?

### ISSUE THREAD

**Issue by blackberrybhtg** [deepmind/abstract-reasoning-matrices#1]
Hello DeepMind team,

Thanks so much for the great work and sharing the dataset!

I downloaded the dataset and tried to visualize it. But I can barely understand any of the images. The visualized examples are attached.
[abstract-reasoning-example.pdf](https://github.com/deepmind/abstract-reasoning-matrices/files/2191153/abstract-reasoning-example.pdf)

My question is whether the images are intended for human to read?

Best regards

**Comment by aiXander** [comment]
I just spent half an hour puzzled over the same isse... I modified your script a little bit and got something that looks better, but still not what it's supposed to be...

According to the paper, the npz files contain 0-255 grayscale intensity values, but even after casting the arrays to np.uint8 and reading them as grayscale luminances with PIL the results still look bad.. 
I then tried to manually rescale the integer values and that seemed to make a difference, but I have no idea what the right solution is here.
 
Anybody know how to fix this?

[explore.pdf](https://github.com/deepmind/abstract-reasoning-matrices/files/2205921/explore.pdf)

**Comment by gupengju** [comment]
The input consisted of the eight context panels and eight
multiple-choice panels. Each panel is an 80×80 pixel
image; so, the panels were presented as a set of 16 feature
maps.
Each panel is an 80× 80 pixel, But why we get  160×160*16 ndarray @tr1pzz ?

**Comment by blackberrybhtg** [comment]
@gupengju 16 is the number of panels. See https://github.com/deepmind/abstract-reasoning-matrices/blob/master/README.md

**Comment by gupengju** [comment]
i wonder why not 80×80×16 array, since each panel is an 80×80 pixel image.

**Comment by blackberrybhtg** [comment]
Yes, I see what you are asking. As per the paper, the data is described as panels of 80*80 pixel images, while the published data is panels of 160*160 pixel images, which may indicate some inconsistency or error.

**Comment by aiXander** [comment]
Anybody found a fix yet? Would love to run some VAE's on this dataset!

**Comment by santoroAI** [comment]
Hi all -- sorry for not spotting this sooner. This is just a shaping issue, I believe.

Images are 160x160 instead of the 80x80 we used in the paper, just in case you want to use higher resolution. Also, I think a simple reshaping should fix the issue regarding human readability, and we'll update the README accordingly. Please try the following:

x = np.load("name_of_file.npz")
y = x['image'].reshape(16, 160, 160) # this reshape is critical 
plt.imshow(y[0], cmap="gray")
plt.show()

The image should look as expected.

**Comment by aiXander** [comment]
Works like a charm, thx!!
[explore.pdf](https://github.com/deepmind/abstract-reasoning-matrices/files/2241391/explore.pdf)

**Comment by blackberrybhtg** [comment]
Thanks so much for the solution! Resolving.
